name: My_plugin
version: ${project.version}
main: de.chris.my_plugin.Main
api-version: 1.16
authors: [ rennmaushunter ]
description: My first plugin

commands:
  timer:
    description: timer
  invsee:
    description: shows inventory of player
  backpack:
    description: opens the backpack
    aliases:
      - bp
  position:
    aliases:
      - pos
    description: adds a position
  World:
    description: creates / enters a world
  challenge:
    description: Starts the given challenge
  coins:
    description: The coin System
  pvp:
    description: Sets the PVP either to the new one (1.9+) or the old one (1.8)
  rdc:
    description: Can only run, when random drop challenge is asking to reset the drops